version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-hello"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-oxr732qymnfk"
s3_prefix = "sam-app-hello"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
